<?php
/**
 * Single source of truth for all case-study pages.
 * Content (role, timeline, tech stack, challenge, solution, impact, testimonials)
 * is moved VERBATIM from the original homepage portfolio modals — restructured,
 * not rewritten. Ordered AI-first; the first 6 entries are the homepage features.
 *
 * NOTE: `datePublished` is intentionally omitted from every case study — the repo
 * has no real publication dates and the pack flags them [CONFIRM]. See MISSING INPUT.
 */

$CASE_STUDIES = [

    'iqbalai' => [
        'name'        => 'IqbalAI',
        'h1'          => 'IqbalAI — AI-First Urdu Educational & School Management Platform',
        'title'       => 'IqbalAI: AI-First Urdu Education Platform | T&M Case Study',
        'meta'        => 'How T&M, as Fractional CTO, shipped an Urdu-enabled AI learning platform in 3–4.5 months using LangGraph, Qdrant and FastAPI — cutting development costs ~70%.',
        'image'       => '/assets/img/portfolio/iqbalai-web.png',
        'image_alt'   => 'IqbalAI Dashboard Screenshot',
        'role'        => 'Fractional CTO & Solutions Architect',
        'timeline'    => '2024 - 2025',
        'tech'        => ['FastAPI (Python 3.12)', 'Next.js (App Router)', 'PostgreSQL 16', 'Qdrant Vector DB', 'LangGraph', 'Piper TTS / whisper'],
        'challenge'   => 'Build an AI-first, Urdu-enabled educational learning management platform and school administration suite. It required tools for teachers to build lectures, quizzes, and curricula, while allowing students to take dynamic AI-supported professional test preps, plus school-tenant separations for managing private/public chains.',
        'solution'    => 'As Fractional CTO, we established a strict AI-native software engineering loop that auto-generates TypeScript client contracts. We developed stateful agent workflows using LangGraph and Pydantic AI, multilingual hybrid vector search (BGE-M3 + Qdrant), Urdu speech-to-text models, and secure school-chain multi-tenant database partitions.',
        'impact'      => ['Compressed development timeline down to 3–4.5 months (saving 70% in costs).', 'Urdu-enabled AI engine helping students, teachers, and admins.', 'Unified Admin panel to control multi-school chains.'],
        'tags'        => ['AI'],
        'private'     => false,
        'live_url'    => 'https://iqbalai.com',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'IqbalAI: AI-First Urdu Educational & School Management Platform',
        'schema_description'  => 'As Fractional CTO, T&M shipped an Urdu-enabled, AI-first learning and school management platform in 3–4.5 months using LangGraph, Qdrant vector search and FastAPI, reducing development costs by approximately 70%.',
        'schema_app_category' => 'EducationalApplication',
        'schema_about_url'    => 'https://iqbalai.com',
        'testimonial' => null,
    ],

    'captureproof' => [
        'name'        => 'CaptureProof',
        'h1'          => 'CaptureProof — Medical Image Analysis Platform',
        'title'       => 'CaptureProof: 99.99% Uptime Medical CV Platform | T&M Case Study',
        'meta'        => 'As Solutions Architect, T&M trained medical computer-vision models and ran HIPAA-compliant AWS infrastructure at 99.99% uptime over 3 years using PyTorch and TensorFlow.',
        'image'       => '/assets/img/portfolio/captureproof-web.png',
        'image_alt'   => 'CaptureProof Interface Screenshot',
        'role'        => 'Solutions Architect & Infrastructure Team',
        'timeline'    => '2023 - 2026 (Past 3 Years)',
        'tech'        => ['PyTorch', 'TensorFlow', 'Python', 'AWS (EC2, S3, RDS, CloudFront)', 'Custom CV Models'],
        'challenge'   => 'Train, validate, and optimize medical computer vision models to track patient visual physiological changes over time, requiring high uptime and strict HIPAA-compliant cloud hosting solutions.',
        'solution'    => 'T&M trained specialized computer vision architectures (non-LLM models) for clinical visual analytics. Over the past 3 years, we have fully managed the secure AWS hosting cluster, engineered automated backups, configured CloudFront CDN distribution, and provided dedicated backend maintenance.',
        'impact'      => ['Maintained 99.99% AWS server cluster availability over 3 years.', 'Successfully satisfied rigorous healthcare data protection audits.', 'Deployed highly accurate visual physiological tracking models.'],
        'tags'        => ['AI'],
        'private'     => true,
        'live_url'    => null,
        'live_label'  => null,
        'schema_headline'     => 'CaptureProof — Medical Image Analysis Platform',
        'schema_description'  => 'As Solutions Architect, T&M trained medical computer-vision models and ran HIPAA-compliant AWS infrastructure at 99.99% uptime over 3 years using PyTorch and TensorFlow.',
        'schema_app_category' => 'MedicalApplication',
        'schema_about_url'    => null,
        'testimonial' => null,
    ],

    'atlas' => [
        'name'        => 'Atlas by BoH',
        'h1'          => 'Atlas by BoH — AI Copilot Platform',
        'title'       => 'Atlas: Real-Time AI Copilot with RAG | T&M Case Study',
        'meta'        => 'T&M\'s AI team built Atlas, a real-time AI copilot with a RAG backend on FastAPI and LangChain, delivering natural-language analytics reports in under 1.5 seconds.',
        'image'       => '/assets/img/portfolio/atlas-web.png',
        'image_alt'   => 'Atlas Dashboard Screenshot',
        'role'        => 'AI Solutions Team & Frontend Engineers',
        'timeline'    => '2024',
        'tech'        => ['React', 'Next.js', 'FastAPI', 'OpenAI API', 'LangChain (RAG)'],
        'challenge'   => 'Develop a premium, responsive real-time AI copilot application with a fluid data-visualizing analytics dashboard querying complex backends.',
        'solution'    => 'We designed a dark-themed user interface featuring interactive charting widgets and multi-agent chat. We developed a robust Retrieval-Augmented Generation (RAG) backend utilizing FastAPI and LangChain, enabling natural language to SQL/report execution.',
        'impact'      => ['Fluid, high-responsiveness dashboard active for Hybrid users.', 'Under 1.5s latency on custom natural language analytics reports.'],
        'tags'        => ['AI'],
        'private'     => false,
        'live_url'    => 'https://atlas.buildonhybrid.com/',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'Atlas by BoH — AI Copilot Platform',
        'schema_description'  => 'T&M\'s AI team built Atlas, a real-time AI copilot with a RAG backend on FastAPI and LangChain, delivering natural-language analytics reports in under 1.5 seconds.',
        'schema_app_category' => 'BusinessApplication',
        'schema_about_url'    => 'https://atlas.buildonhybrid.com/',
        'testimonial' => null,
    ],

    'otto' => [
        'name'        => 'OTTO by BoH',
        'h1'          => 'OTTO by BoH — Autonomous AI Agent',
        'title'       => 'OTTO: Autonomous On-Chain AI Agent | T&M Case Study',
        'meta'        => 'T&M\'s AI agents team built OTTO, a fully autonomous on-chain AI agent on Pydantic AI that monitors blockchains and executes secure transactions from natural-language prompts.',
        'image'       => '/assets/img/portfolio/otto-web.png',
        'image_alt'   => 'OTTO AI Agent Screenshot',
        'role'        => 'AI Agents Team & Project Management',
        'timeline'    => '2024',
        'tech'        => ['Pydantic AI', 'Python', 'Hybrid API', 'Web3.js', 'Social API integrations'],
        'challenge'   => 'Develop an autonomous AI agent capable of parsing natural language prompts, monitoring live blockchain networks, executing secure transactions, and communicating findings across social channels.',
        'solution'    => 'We built OTTO\'s agentic decision workflows using Pydantic AI. We integrated the Hybrid Unified Data API so the agent fetches audited Web3 telemetry, and programmed cryptographically constrained transaction tools to guarantee safe agent wallet operations.',
        'impact'      => ['100% autonomous agent running on live social and crypto channels.', 'Integrated directly with wallets supporting automated gas limits.'],
        'tags'        => ['AI', 'Web3'],
        'private'     => false,
        'live_url'    => 'https://onchainotto.ai/',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'OTTO by BoH — Autonomous AI Agent',
        'schema_description'  => 'T&M\'s AI agents team built OTTO, a fully autonomous on-chain AI agent on Pydantic AI that monitors blockchains and executes secure transactions from natural-language prompts.',
        'schema_app_category' => 'BusinessApplication',
        'schema_about_url'    => 'https://onchainotto.ai/',
        'testimonial' => null,
    ],

    'docushield' => [
        'name'        => 'Docushield',
        'h1'          => 'Docushield — Secure Document Verification Platform',
        'title'       => 'Docushield: Blockchain Document Verification | T&M Case Study',
        'meta'        => 'As Fractional CTO, T&M shipped Docushield\'s blockchain document-verification apps on custom L2 nodes and Solidity — the client raised $0.5M in seed funding.',
        'image'       => '/assets/img/portfolio/doc-web.png',
        'image_alt'   => 'Docushield Interface Screenshot',
        'role'        => 'Fractional CTO & Solutions Architect',
        'timeline'    => '2020 - 2021',
        'tech'        => ['Solidity', 'Web3.js', 'iOS (Swift)', 'Android (Kotlin)', 'PHP Web Admin', 'L2 Blockchain'],
        'challenge'   => 'The requirement was to deliver an enterprise-grade document sharing, signing, and verification mobile and web application backed by secure, distributed ledger infrastructure to assure document integrity.',
        'solution'    => 'As Fractional CTO, we designed and deployed custom Layer 2 (L2) blockchain nodes to index document hashes securely. We also launched the native $DOC utility token, built native iOS and Android apps, created a PHP web console, and managed the full engineering and QA teams.',
        'impact'      => ['Raised $0.5 Million in seed funding.', '100% auditable blockchain-backed document signatures.'],
        'tags'        => ['App', 'Web3'],
        'private'     => true,
        'live_url'    => null,
        'live_label'  => null,
        'schema_headline'     => 'Docushield — Secure Document Verification Platform',
        'schema_description'  => 'As Fractional CTO, T&M shipped Docushield\'s blockchain document-verification apps on custom L2 nodes and Solidity — the client raised $0.5M in seed funding.',
        'schema_app_category' => 'BusinessApplication',
        'schema_about_url'    => null,
        'testimonial' => [
            'quote'  => 'T&M went above and beyond in development of my project. They not only assisted with the project development but also helped me refine my idea. I was thoroughly impressed with the speed of delivery as the project was time sensitive. I would strongly recommend working with them. Thanks again and looking forward to working with you in future.',
            'img'    => '/assets/img/doc-circle.png',
            'name'   => 'Jules Mancion (Project Manager)',
            'source' => 'docushield.com',
            'url'    => 'https://docushield.tnmco.uk/',
        ],
    ],

    'nonrival-data' => [
        'name'        => 'NonRival Data',
        'h1'          => 'NonRival Data — Web 3.0 Data Platform',
        'title'       => 'NonRival Data: Web3 Data Monetization MVP | T&M Case Study',
        'meta'        => 'As Fractional CTO, T&M launched NonRival Data\'s privacy-first Web3 MVP across web, iOS, Android and 3 extension stores using Laravel, React Native and Solidity.',
        'image'       => '/assets/img/portfolio/nrd-web.png',
        'image_alt'   => 'NonRival Data Dashboard Screenshot',
        'role'        => 'Fractional CTO & Lead Product Delivery',
        'timeline'    => '2021 - 2022',
        'tech'        => ['Laravel 8', 'React Native', 'Web3.js', 'Solidity', 'Infura', 'Browser Extensions API'],
        'challenge'   => 'The client wanted to build a privacy-first, MVP blockchain ecosystem empowering users to take control of their financial data and monetize it. This required seamless cross-platform functionality spanning Web, Mobile (iOS/Android), and major Web Browsers (Chrome, Firefox, Safari, Brave).',
        'solution'    => 'T&M designed and engineered a unified ecosystem. We built high-performance browser extensions, responsive mobile applications, and secure Ethereum mainnet hooks via Infura. All user transactions securely record hashes to custom Solidity smart contracts, utilizing client-side cryptographic hashing to keep raw data completely private.',
        'impact'      => ['Successfully launched Web 3.0 MVP across Web, iOS, Android, and 3 Extension Stores.', '100% of user data monetization requests validated on the Ethereum mainnet.', 'Designed high-performance cross-platform communication protocols.'],
        'tags'        => ['Web3', 'App', 'Web'],
        'private'     => false,
        'live_url'    => 'https://nonrivaldata.com',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'NonRival Data — Web 3.0 Data Platform',
        'schema_description'  => 'As Fractional CTO, T&M launched NonRival Data\'s privacy-first Web3 MVP across web, iOS, Android and 3 extension stores using Laravel, React Native and Solidity.',
        'schema_app_category' => 'BusinessApplication',
        'schema_about_url'    => 'https://nonrivaldata.com',
        'testimonial' => null,
    ],

    'build-on-hybrid' => [
        'name'        => 'Build On Hybrid',
        'h1'          => 'Build On Hybrid — Web3 Node Infrastructure',
        'title'       => 'Build On Hybrid: Web3 Node Infrastructure | T&M Case Study',
        'meta'        => 'As Solutions Architect, T&M designed Build On Hybrid\'s decentralized node infrastructure and Unified Data API using Go, Rust and Node.js for multichain Web3 networks.',
        'image'       => '/assets/img/portfolio/buildonhybrid-web.png',
        'image_alt'   => 'Build On Hybrid Platform Screenshot',
        'role'        => 'Solutions Architect & Project Management',
        'timeline'    => '2023 - 2024',
        'tech'        => ['Go', 'Rust', 'Node.js', 'Web3 Node Infrastructure', 'GraphQL API'],
        'challenge'   => 'Design a decentralized node deployment architecture and a high-performance Unified Data API for multichain Web3 networks, enabling developers to query audited blockchain records instantly.',
        'solution'    => 'T&M provided fractional architecture consulting. We designed the Go and Rust based node indexing infrastructure, mapped the Unified Data API models, and built the developer portal hub and API playgound (docs.buildonhybrid.com).',
        'impact'      => ['Guided project from raw ideation to verified technical architecture blueprints.', 'Deployed high-availability node query infrastructure worldwide.'],
        'tags'        => ['Web3'],
        'private'     => true,
        'live_url'    => null,
        'live_label'  => null,
        'schema_headline'     => 'Build On Hybrid — Web3 Node Infrastructure',
        'schema_description'  => 'As Solutions Architect, T&M designed Build On Hybrid\'s decentralized node infrastructure and Unified Data API using Go, Rust and Node.js for multichain Web3 networks.',
        'schema_app_category' => 'DeveloperApplication',
        'schema_about_url'    => null,
        'testimonial' => null,
    ],

    'quickcard' => [
        'name'        => 'QuickCard (now RYVYL)',
        'h1'          => 'QuickCard (now RYVYL) — Contactless Payment Platform',
        'title'       => 'QuickCard: Cashless Payments to NASDAQ Exit | T&M Case Study',
        'meta'        => 'As Fractional CTO, T&M built QuickCard\'s contactless payment ecosystem on React, Django and Stripe — later acquired and transitioned into NASDAQ-listed RYVYL.',
        'image'       => '/assets/img/portfolio/qc.png',
        'image_alt'   => 'QuickCard Logo',
        'role'        => 'Fractional CTO & Lead Payments Engineer',
        'timeline'    => '2020 - 2021',
        'tech'        => ['React', 'Python', 'Django', 'PostgreSQL', 'Stripe API', 'POS Integrations'],
        'challenge'   => 'Develop a contactless and cashless payment ecosystem allowing merchants to create bills, generate printable/digital QR codes, and hook directly into hardware card readers.',
        'solution'    => 'We created custom Stripe checkout integrations, designed merchant dashboard panels to log daily transaction logs, set up PostgreSQL databases, and integrated POS card reader APIs.',
        'impact'      => ['Contactless transaction ecosystem fully deployed.', 'Acquired and transitioned into RYVYL (now publicly traded on NASDAQ).', 'Integrated POS card readers successfully processing payments.'],
        'tags'        => ['Web'],
        'private'     => false,
        'live_url'    => 'https://www.ryvyl.com/',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'QuickCard (now RYVYL) — Contactless Payment Platform',
        'schema_description'  => 'As Fractional CTO, T&M built QuickCard\'s contactless payment ecosystem on React, Django and Stripe — later acquired and transitioned into NASDAQ-listed RYVYL.',
        'schema_app_category' => 'FinanceApplication',
        'schema_about_url'    => 'https://www.ryvyl.com/',
        'testimonial' => null,
    ],

    'e-sehat' => [
        'name'        => 'e-Sehat',
        'h1'          => 'e-Sehat — Telemedicine Mobile App',
        'title'       => 'e-Sehat: HIPAA Telemedicine App | T&M Case Study',
        'meta'        => 'As mobile developers, T&M shipped e-Sehat, a HIPAA-compliant telemedicine app with encrypted WebRTC video consultations built on React Native and Node.js.',
        'image'       => '/assets/img/portfolio/esehat.png',
        'image_alt'   => 'e-Sehat App Screenshot',
        'role'        => 'Mobile Developers & Video Streaming Engineers',
        'timeline'    => '2021 - 2022',
        'tech'        => ['React Native', 'Node.js', 'MongoDB', 'WebRTC (Real-time Video)'],
        'challenge'   => 'Develop a highly secure, HIPAA-compliant telemedicine application connecting patients in Pakistan to specialized doctors, supporting live slot booking, instant video calls, and e-prescriptions.',
        'solution'    => 'T&M developed cross-platform mobile apps using React Native. We built encrypted, low-bandwidth WebRTC video consultation rooms, constructed database booking engines, and integrated local digital wallets for deposit methods.',
        'impact'      => ['HIPAA-compliant video telemedicine app successfully launched.', 'Low-latency, encrypted consultations running on mobile devices.'],
        'tags'        => ['App'],
        'private'     => false,
        'live_url'    => 'https://play.google.com/store/apps/details?id=com.tnm.e_sehat&fbclid=IwAR132Dx6zlIK9nwDyRF1iq4s8LSTbZ6-SW3VMqvICqb5NDSGsWns1MvTREI',
        'live_label'  => 'View on Play Store',
        'schema_headline'     => 'e-Sehat — Telemedicine Mobile App',
        'schema_description'  => 'As mobile developers, T&M shipped e-Sehat, a HIPAA-compliant telemedicine app with encrypted WebRTC video consultations built on React Native and Node.js.',
        'schema_app_category' => 'HealthApplication',
        'schema_about_url'    => 'https://play.google.com/store/apps/details?id=com.tnm.e_sehat',
        'testimonial' => null,
    ],

    'mintit-studio' => [
        'name'        => 'MintIt Studio',
        'h1'          => 'MintIt Studio — NFT Marketplace on Kadena',
        'title'       => 'MintIt Studio: First Kadena NFT Marketplace | T&M Case Study',
        'meta'        => 'As Fractional CTO, T&M launched the first mutant-NFT marketplace on Kadena using Pact smart contracts and React.js — with zero post-launch security vulnerabilities.',
        'image'       => '/assets/img/portfolio/mintit-web.png',
        'image_alt'   => 'MintIt Studio Marketplace Screenshot',
        'role'        => 'Fractional CTO & Lead Smart Contract Developer',
        'timeline'    => '2021 - 2022',
        'tech'        => ['Kadena Blockchain', 'Pact Smart Contracts', 'React.js', 'Docker', 'CI/CD'],
        'challenge'   => 'Design and develop the first NFT marketplace on the Kadena Ecosystem featuring dynamic "mutant" NFTs that evolve based on on-chain activities.',
        'solution'    => 'We authored secure Pact smart contracts, set up Kadena gas station relays to subsidize user transactions, designed the React.js integration, and built deployment infrastructure using Docker and automated CI/CD pipelines.',
        'impact'      => ['Successfully launched the first-ever mutant NFT marketplace on Kadena.', 'Zero security vulnerabilities reported post-launch.'],
        'tags'        => ['Web', 'Web3'],
        'private'     => false,
        'live_url'    => 'https://mintit.tnmco.uk/',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'MintIt Studio — NFT Marketplace on Kadena',
        'schema_description'  => 'As Fractional CTO, T&M launched the first mutant-NFT marketplace on Kadena using Pact smart contracts and React.js — with zero post-launch security vulnerabilities.',
        'schema_app_category' => 'BusinessApplication',
        'schema_about_url'    => 'https://mintit.tnmco.uk/',
        'testimonial' => null,
    ],

    'tameer-estate' => [
        'name'        => 'Tameer Estate UK',
        'h1'          => 'Tameer Estate UK — Property Search Portal',
        'title'       => 'Tameer Estate: UK Property Search Portal | T&M Case Study',
        'meta'        => 'As the full-stack web team, T&M built Tameer Estate UK, a responsive property search portal on WordPress, PHP and the Google Maps API with custom filters.',
        'image'       => '/assets/img/portfolio/tameer-web.png',
        'image_alt'   => 'Tameer Estate UK Website Screenshot',
        'role'        => 'Full Stack Web Team',
        'timeline'    => '2020 - 2021',
        'tech'        => ['WordPress', 'PHP', 'MySQL', 'Google Maps API', 'Custom Search Queries'],
        'challenge'   => 'Develop a highly performant UK-focused property directory platform supporting sales, rentals, builder profiles, interactive location-based searching, and custom property filters.',
        'solution'    => 'We built custom database query systems to instantly filter properties by geography, pricing thresholds, and room specifications. We embedded dynamic Google Maps features showing location markers and nearby points of interest.',
        'impact'      => ['Fully responsive UK property search portal successfully deployed.', 'Integrated instant location mapping system with 100% automated map syncing.'],
        'tags'        => ['Web'],
        'private'     => false,
        'live_url'    => 'https://tameerestate.com',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'Tameer Estate UK — Property Search Portal',
        'schema_description'  => 'As the full-stack web team, T&M built Tameer Estate UK, a responsive property search portal on WordPress, PHP and the Google Maps API with custom filters.',
        'schema_app_category' => 'BusinessApplication',
        'schema_about_url'    => 'https://tameerestate.com',
        'testimonial' => [
            'quote'  => 'I\'m thrilled to share my experience working with T&M consultants on our real estate website project. Their expertise in creating a platform for property sale, purchase, and rental, along with detailed builder information, was exceptional. T&M consultants seamlessly integrated features like property search, virtual tours, and secure payments. Their innovation, including augmented reality tools, elevated our platform above the competition. Communication was excellent throughout, and T&M consultants tackled challenges with dedication, ensuring a flawless user experience by launch day. I wholeheartedly recommend T&M consultants for their technical skills, user-centric approach, and transformative contributions to our project. Thank you for shaping the future of real estate online!',
            'img'    => '/assets/img/tameer_circle.png',
            'name'   => 'Hamza Bajwa (Project Manager)',
            'source' => 'tameerestate.com',
            'url'    => 'https://tameerestate.com/',
        ],
    ],

    'tiny-crews' => [
        'name'        => 'Tiny Crews',
        'h1'          => 'Tiny Crews — Kids Clothing E-Commerce Store',
        'title'       => 'Tiny Crews: Shopify Kids Store, 90+ Speed | T&M Case Study',
        'meta'        => 'As e-commerce developers, T&M built Tiny Crews\' Shopify storefront in Liquid, lifting mobile page-load to 90+ and cutting cart abandonment by 15%.',
        'image'       => '/assets/img/portfolio/tinycrews-web.png',
        'image_alt'   => 'Tiny Crews Storefront Screenshot',
        'role'        => 'E-Commerce Developers & Storefront Designers',
        'timeline'    => '2022 - 2023',
        'tech'        => ['Shopify', 'Liquid', 'JavaScript', 'Custom Checkout APIs'],
        'challenge'   => 'Create a highly responsive, custom boutique kids clothing storefront on Shopify with clean, fast checkout, custom cart behaviors, and real-time inventory sync.',
        'solution'    => 'T&M developed a responsive theme utilizing Shopify Liquid and vanilla JavaScript. We optimized page speed configurations and implemented direct inventory and notification synchronization hooks.',
        'impact'      => ['Reduced checkout cart abandonment rates by 15%.', 'Increased mobile page-load speed score to 90+.'],
        'tags'        => ['E-commerce', 'Web'],
        'private'     => false,
        'live_url'    => 'https://tinycrews.com/',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'Tiny Crews — Kids Clothing E-Commerce Store',
        'schema_description'  => 'As e-commerce developers, T&M built Tiny Crews\' Shopify storefront in Liquid, lifting mobile page-load to 90+ and cutting cart abandonment by 15%.',
        'schema_app_category' => 'ShoppingApplication',
        'schema_about_url'    => 'https://tinycrews.com/',
        'testimonial' => null,
    ],

    'his-and-hers' => [
        'name'        => 'His & Hers',
        'h1'          => 'His & Hers — Fashion E-Commerce Storefront',
        'title'       => 'His & Hers: High-Traffic Fashion Store | T&M Case Study',
        'meta'        => 'As e-commerce developers, T&M delivered His & Hers, a high-traffic WooCommerce fashion store with PHP query optimization and automated SMS confirmations.',
        'image'       => '/assets/img/portfolio/hisandhers-web.png',
        'image_alt'   => 'His & Hers Storefront Screenshot',
        'role'        => 'E-Commerce Developers & UI Designers',
        'timeline'    => '2022 - 2023',
        'tech'        => ['WordPress', 'WooCommerce', 'PHP', 'Custom Payment APIs', 'SMS Gateway API'],
        'challenge'   => 'Build a premium, high-traffic clothing e-commerce storefront for a prominent fashion brand in Pakistan. The system needed database optimization to survive flash-sales spikes and custom local API hooks.',
        'solution'    => 'T&M delivered a premium dark-gold themed WooCommerce storefront, implementing direct PHP query optimizations, custom checkout integrations, and automated SMS confirmation networks.',
        'impact'      => ['Platform handles thousands of concurrent checkouts during seasonal sales.', 'Integrated automated SMS billing alerts for clients.'],
        'tags'        => ['E-commerce', 'Web'],
        'private'     => false,
        'live_url'    => 'https://hisandhers.com.pk',
        'live_label'  => 'Visit Live Site',
        'schema_headline'     => 'His & Hers — Fashion E-Commerce Storefront',
        'schema_description'  => 'As e-commerce developers, T&M delivered His & Hers, a high-traffic WooCommerce fashion store with PHP query optimization and automated SMS confirmations.',
        'schema_app_category' => 'ShoppingApplication',
        'schema_about_url'    => 'https://hisandhers.com.pk',
        'testimonial' => null,
    ],

];
